[build]
  command = "npx expo export --platform web && node scripts/inject-manifest.js"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
